CREATE TABLE ALUNO (
    id_aluno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    matricula VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(150),
    telefone VARCHAR(20),
    tem_pendencia BOOLEAN DEFAULT FALSE
);

CREATE TABLE EQUIPAMENTO (
    id_equipamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    numero_serie VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    status VARCHAR(50),
    data_aquisicao DATE,
    quantidade INTEGER DEFAULT 1
);

CREATE TABLE EMPRESTIMO (
    id_emprestimo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno INTEGER NOT NULL,
    id_equipamento INTEGER NOT NULL,
    data_emprestimo TIMESTAMP NOT NULL,
    data_devolucao_prevista TIMESTAMP NOT NULL,
    data_devolucao_real TIMESTAMP,
    observacoes TEXT,
    CONSTRAINT fk_emprestimo_aluno FOREIGN KEY (id_aluno) REFERENCES ALUNO(id_aluno),
    CONSTRAINT fk_emprestimo_equipamento FOREIGN KEY (id_equipamento) REFERENCES EQUIPAMENTO(id_equipamento)
);